### PR TITLE
Give the compiled test the same base URI as the uncompiled test

### PR DESCRIPTION
**Pull request by bertfrees**

### CODE REVIEW

**Comment by bertfrees** [comment]
bump!

**Comment by bertfrees** [comment]
@rdeltour You probably forgot this one too so here is a reminder :) Or is there something wrong with the patch?

**Comment by bertfrees** [comment]
thnx!

**Comment by bertfrees** [comment]
@rdeltour Can we make a release 1.0.1?

**Comment by rdeltour** [comment]
@bertfrees sure, go ahead.

**Pull request merged**
